version: '3.9'

services:
  databasecota:
    image: postgres:17
    container_name: databasecota
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

  backendcota:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backendcota
    restart: always
    depends_on:
      databasecota:
        condition: service_healthy
      rediscota:
        condition: service_healthy
    # para testar
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network

  rediscota:
    image: redis:7.2-alpine
    container_name: rediscota
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network


volumes:
  postgres_data:
  redis_data:

networks:
  app_network: